apiVersion: v1
kind: LimitRange
metadata:
  name: cpu-resource-constraint
  namespace: mani
spec:
  limits:
    - max: 
       cpu: "200m"
       memory: "500Mi"
      min: 
       cpu: "100m"
       memory: "100Mi"

      type: Container