apiVersion: v1
kind: Pod
metadata:
 name: mani
 namespace: mani
spec:
 containers:
 - name: mani
   image: imr99/ecomm
   ports:
   - containerPort: 80
   resources:
     limits:
       cpu: "2"
       memory: 1Gi