apiVersion: v1
kind: Pod
metadata:
  name: raghu
  namespace: mani
  labels: 
     name: raw-volume
spec:
  containers:
  - image: nginx
    name: test-container
    volumeMounts:
    - mountPath: /usr/share/nginx/html/
      name: test-volume
  volumes:
  - name: test-volume
    # This AWS EBS volume must already exist.
    awsElasticBlockStore:
      volumeID: vol-014568c9b00d48556
      fsType: ext4