apiVersion: apps/v1
kind: Deployment
metadata:
  name: mani
  namespace: mani
  labels:
    app: mani
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mani
  template:
    metadata:
      labels:
        app: mani
    spec:
      containers:
      - name: mani
        image: imr99/ecomm
        ports:
        - containerPort: 80
        readinessProbe:
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 10
            successThreshold: 1
            failureThreshold: 3
            httpGet:
                path: /
                port: 80