apiVersion: v1
kind: PersistentVolume
metadata:
  name: aws-pv1
  namespace: mani
  labels:
    type: aws-pv1
spec:
  storageClassName: gp2
  persistentVolumeReclaimPolicy: Delete
  capacity:
    storage: 2Gi
  accessModes:
  - ReadWriteOnce
  awsElasticBlockStore:
    volumeID: vol-014568c9b00d48556
    fsType: ext4