apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: task-pv-claim1
  namespace: mani
spec:
  storageClassName: gp2
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi