apiVersion: v1
kind: ReplicationController
metadata:
  name: mani
  namespace: mani
spec:
  replicas: 3
  selector:
    app: mani
  template:
    metadata:
      name: mani
      labels:
        app: mani
    spec:
      containers:
      - name: mani
        image: imr99/ecomm
        ports:
        - containerPort: 80