apiVersion: v1
kind: ResourceQuota
metadata:
 name: object-counts
 namespace: mani
spec:
 hard:
   requests.cpu: "1000m"
   limits.cpu: "2000m"
   requests.memory: "1Gi"
   limits.memory: "2Gi"
